### PR TITLE
Add webm support.

### PR DESCRIPTION
**Pull request by ghost**
Works for me. Try it out.

Here's a thread with some demos https://boards.4chan.org/g/res/41338578

As an added bonus, whatever auto-detection moot was adding in to stop embedding with images doesn't work with webm. Don't tell him, he hates fun.

### CODE REVIEW

**Comment by dnsev** [comment]
Unsurprising really, that the same extra data form works.

I'll see if I can get some more proper support for this tomorrow or so. Wait warmly.

**Comment by dnsev** [comment]
So .webm + sound support should be added in [5.1](https://github.com/dnsev/4cs/commit/26f450a5b7abbd18e7ffab480bc1dd640adbaa89)/[cl](http://dnsev.github.io/4cs/#changes?highlight=5_1&scroll=5_1)

It should now display the video also, and try and sync it properly if the lengths are the same.

Tested only with [the archive](http://archive.foolz.us/a/thread/105524960/#105538867) so far, but it'll probably work elsewhere.

Time to start placing bets on how long this takes to get blocked.

**Comment by ghost** [comment]
Nice, this is exactly what I was hoping for, being able to embed the video and sync audio to it. Great job.

Here's hoping there's some reason he can't block them with webms.

**Comment by Matrius** [comment]
Seems to be already detected. Welp, funs over.

**Pull request closed without merging**
